# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vehicle_edge.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'vehicle_edge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12vehicle_edge.proto\"\x1d\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"\x1f\n\rImageResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"+\n\x0cRouteRequest\x12\r\n\x05start\x18\x01 \x01(\t\x12\x0c\n\x04goal\x18\x02 \x01(\t\"\x1d\n\rRouteResponse\x12\x0c\n\x04path\x18\x01 \x01(\t2g\n\nEdgeServer\x12-\n\x0cProcessImage\x12\r.ImageRequest\x1a\x0e.ImageResponse\x12*\n\tPlanRoute\x12\r.RouteRequest\x1a\x0e.RouteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vehicle_edge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=22
  _globals['_IMAGEREQUEST']._serialized_end=51
  _globals['_IMAGERESPONSE']._serialized_start=53
  _globals['_IMAGERESPONSE']._serialized_end=84
  _globals['_ROUTEREQUEST']._serialized_start=86
  _globals['_ROUTEREQUEST']._serialized_end=129
  _globals['_ROUTERESPONSE']._serialized_start=131
  _globals['_ROUTERESPONSE']._serialized_end=160
  _globals['_EDGESERVER']._serialized_start=162
  _globals['_EDGESERVER']._serialized_end=265
# @@protoc_insertion_point(module_scope)
